name: rss

on:
  schedule:
  - cron: '0 */12 * * *'

jobs:
  new-traces:
    runs-on: ubuntu-latest
    steps:
    - uses: guilhem/rss-issues-action@0.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        feed: "https://www.openstreetmap.org/traces/tag/bus%20route/rss"
        prefix: "[Trace]"
        dry-run: "false"
        lastTime: "13h"
        labels: "à qualifier"
